import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import {
  RegisterLink,
  LoginLink,
  LogoutLink,
} from "@kinde-oss/kinde-auth-nextjs/components";
import { getKindeServerSession } from "@kinde-oss/kinde-auth-nextjs/server";

export default async function RootLayout({ children }) {
  const { getUser, isAuthenticated } = getKindeServerSession();
  const user = await getUser();
  return (
    <html lang="en" className="p-6">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="flex justify-between items-center">
          <div>
            <Link href="/">
              <h3 className="text-xl md:text-2xl font-bold">Next Project</h3>
            </Link>
          </div>
          <ul className="flex gap-5">
            <li className="text-xl font-bold">
              <Link href="/">Home</Link>
            </li>
            <li className="text-xl font-bold">
              <Link href="/profile">Profile</Link>
            </li>
          </ul>
          <div className="mb-3">
            {(await isAuthenticated()) ? (
             <button className="text-xl bg-green-500 text-white px-4 py-1 rounded-lg"><LogoutLink>Logout</LogoutLink></button>
            ) : (
              <div className="flex gap-3 items-center">
                <button className="text-xl bg-green-500 text-white px-4 py-1 rounded-lg"><RegisterLink>Sign up</RegisterLink></button>
                <button className="text-xl bg-green-500 text-white px-4 py-1 rounded-lg"><LoginLink>Sign in</LoginLink></button>
              </div>
            )}
          </div>
        </nav>
        <hr />
        {children}
      </body>
    </html>
  );
}
